### ISSUE TITLE
HxD 2.5.0.0 is available

### ISSUE THREAD

**Issue by AJDurant** [ComFreek/chocolatey-packages#22] opened 2022-01-05 11:30 UTC
There has been a new version of HxD since February 11, 2021

**Comment by koitsu** [comment] 2022-11-18 10:02
The [au script](https://github.com/ComFreek/chocolatey-packages/blob/master/hxd/update.ps1#L26) references https://mh-nexus.de/updates/HxDCurrentVersion.json which is maintained by the HxD author.  I couldn't find any reference to this .json file anywhere on his site, but I did find mention of it [on his own forum](https://forum.mh-nexus.de/viewtopic.php?f=4&t=944).  Said author hasn't updated his own .json file to reflect the 2.5.0.0 version; I suspect he's forgotten about this file, so it's probably best not to bother reading/parsing it and instead just do things the old-fashioned way.

**Comment by koitsu** [comment] 2022-11-28 10:14
I've opened a HxD forum post about this problem: https://forum.mh-nexus.de/viewtopic.php?f=3&t=1211

**Comment by maelh** [comment] 2022-12-03 13:27
I updated the DB and wrote code to automatically generate this JSON file, so in future it would be in synch with the download page automatically. Before replacing the current JSON file ( https://mh-nexus.de/updates/HxDCurrentVersion.json ), please see the comments I wrote in the forum post linked in the comment above, so we can agree on what format works best.

**Comment by maelh** [comment] 2022-12-04 16:04
@koitsu It looks like the two maintainers of the Chocolatey package are not engaged with this anymore (also looking at the time of last commits). So I suppose if you or @AJDurant want to take up the task, that would be the most likely to get this rolling again.

**Comment by koitsu** [comment] 2022-12-04 19:05
@maelh Hi! I didn't know you had a GitHub account :) Nice to see you here.  I will try to work on a PR to make @ComFreek 's job a little easier.  But probably won't have time until this coming weekend.

**Comment by AJDurant** [comment] 2022-12-05 11:57
Thanks @koitsu and @maelh for your work on this issue.

Given there's been no response or updates from @ComFreek on this (or indeed at all on GitHub 😕) this might need a new maintainer to get it updated. @mmanela is also listed as a maintainer on Chocolatey

**Comment by koitsu** [comment] 2022-12-06 01:48
@AJDurant Understood. If owner or @mmanela aren't available, uninterested, etc. I'd be happy to take over package ownership.  There is a triage process which has to be followed for that to happen, however, and requires the Chocolatey team be involved: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process

Let's give things a week from today and see if Matthew responds.

**Comment by koitsu** [comment] 2022-12-06 09:29
@maelh I can confirm the "newer JSON format" will work with this Chocolatey package's updater, only requiring a one line change (ignore the `$uri` change in the diff, obviously).  Feel free to push that syntax change out to https://mh-nexus.de/updates/HxDCurrentVersion.json at your convenience (doing so **will not** break existing or new Chocolatey `hxd` package downloads, given how this package was set up).

```diff
diff --git a/hxd/update.ps1 b/hxd/update.ps1
index 71463c8..fbcf7ab 100644
--- a/hxd/update.ps1
+++ b/hxd/update.ps1
@@ -23,12 +23,12 @@ function global:au_SearchReplace {
 }

 function global:au_GetLatest {
-       $uri = 'https://mh-nexus.de/updates/HxDCurrentVersion.json'
+       $uri = 'https://mh-nexus.de/HxD2.5.0.0-installable-BCP47-Language-Tags.json'
        $latestData = Invoke-WebRequest -Uri $uri -UserAgent "Update checker of Chocolatey Community Package 'HxD'" | ConvertFrom-Json

        # The checksum will be computed by Get-RemoteFiles in au_BeforeUpdate().
        return @{
-               URL32 = $latestData.'Download-URI';
+               URL32 = $latestData.'Download-URI'.'*';
                Version = $latestData.'Version';
        }
 }
```

Test results:
```
PS Q:\work\chocolatey-packages-ComFreek\hxd> .\update.ps1
hxd - checking updates using au version 2022.10.24

URL check
  https://mh-nexus.de/downloads/HxDSetup.zip
nuspec version: 2.3.0.0
remote version: 2.5.0.0
New version is available
Automatic checksum skipped
Running au_BeforeUpdate
Purging zip
Downloading to HxDSetup.zip - https://mh-nexus.de/downloads/HxDSetup.zip
Setting package description from README.md
Updating files
  $Latest data:
    Checksum32                (String)     EA97D98877342D725ADCBFA075D5D5770470CF4A1D79477D577D299B6298D62F9A7FEC8903633F8ADCDA7D306BFF848751F8C788B611CC2D1074624A9153BC49
    ChecksumType32            (String)     sha512
    FileName32                (String)     HxDSetup.zip
    FileType                  (String)     zip
    NuspecVersion             (String)     2.3.0.0
    PackageName               (String)     hxd
    URL32                     (String)     https://mh-nexus.de/downloads/HxDSetup.zip
    Version                   (String)     2.5.0.0
  hxd.nuspec
    setting id: hxd
    updating version: 2.3.0.0 -> 2.5.0.0
  .\tools\VERIFICATION.txt
    (^.*)(tools/HxDSetup.zip SHA-512: )([a-zA-Z0-9]+)(.*$) = ${1}${2}EA97D98877342D725ADCBFA075D5D5770470CF4A1D79477D577D299B6298D62F9A7FEC8903633F8ADCDA7D306BFF848751F8C788B611CC2D1074624A9153BC49${4}
  tools\chocolateyInstall.ps1
    (^[$]checksum32\s*=\s*)('.*')       = $1'EA97D98877342D725ADCBFA075D5D5770470CF4A1D79477D577D299B6298D62F9A7FEC8903633F8ADCDA7D306BFF848751F8C788B611CC2D1074624A9153BC49'
  hxd.nuspec
    <version>[^<]*</version>            = <version>2.5.0.0</version>
Running au_AfterUpdate
Setting package description from README.md
Attempting to build package from 'hxd.nuspec'.
Successfully created package 'Q:\work\chocolatey-packages-ComFreek\hxd\hxd.2.5.0.0.nupkg'

Package updated

Path          : Q:\work\chocolatey-packages-ComFreek\hxd
Name          : hxd
Updated       : True
Pushed        : False
RemoteVersion : 2.5.0.0
NuspecVersion : 2.3.0.0
Result        : {hxd - checking updates using au version 2022.10.24, , URL check,
                https://mh-nexus.de/downloads/HxDSetup.zip...}
Error         :
NuspecPath    : Q:\work\chocolatey-packages-ComFreek\hxd\hxd.nuspec
NuspecXml     : #document
Ignored       : False
IgnoreMessage :
StreamsPath   : Q:\work\chocolatey-packages-ComFreek\hxd\hxd.json
Streams       :

PS Q:\work\chocolatey-packages-ComFreek\hxd> dir *.nupkg
    Directory: Q:\work\chocolatey-packages-ComFreek\hxd
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2022-12-06     01:22        3357521 hxd.2.5.0.0.nupkg

PS Q:\work\chocolatey-packages-ComFreek\hxd> dir .\tools\HxDSetup.zip
    Directory: Q:\work\chocolatey-packages-ComFreek\hxd\tools
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2022-12-06     01:22        3348036 HxDSetup.zip
```

**Comment by maelh** [comment] 2022-12-07 02:41
@koitsu  Thanks for the quick update!

While looking at the file format/JSON file and how it's read in the old code, I noticed most of the information is not really processed. But I wonder if Chocolatey lists the available languages and uses the hashes and the list of supported Windows versions. (Edit: I see the hashes are used!)

That's why I documented the format and took care to use standardized identifiers for Windows versions and language identifiers/tags, so the user can be informed what's available.

**Comment by maelh** [comment] 2022-12-07 02:53
I looked at the code and compared it with FoxitReader, which provides options to set the installed language and other tasks during the installation: https://github.com/ComFreek/chocolatey-packages/tree/master/foxitreader

Since the HxDSetup is multi-lingual and also based on InnoSetup I think it would make sense to expose that.

**Comment by koitsu** [comment] 2022-12-07 03:03
@maelh I think that's doable but probably in a separate ticket/issue, as this one's just about trying to get the package updated to 2.5.0.0. :)

**Comment by koitsu** [comment] 2022-12-13 07:08
> Let's give things a week from today and see if Matthew responds.

It's now been over a week.  I'll begin the Chocolatey process of trying to become a maintainer of this package.

**Comment by koitsu** [comment] 2022-12-13 10:06
I've submit a message to the Chocolatey Community Admins, requesting to become the new hxd package maintainer.

I've prepped for this by migrating ComFreek's hxd package (and the associated GitHub commit history for it) into my own repository, and then making many changes that are aligned better with how packages today tend to work, e.g.
- No longer package the HxDSetup.zip file within the Chocolatey package itself; instead `choco install` will fetch the .zip from the official download location (per JSON manifest).  This keeps the Chocolatey package very small, and lets the HxD maintainer see how many people are fetching his software (via web logs, etc.); Chocolatey tends to prefer things be done this way now
- Prepped for the upcoming 2.5.0.0 JSON manifest change (code is commented out for now)
- Replacing the updater script (I have never gotten `au` to behave properly, especially on Windows 7, so I use Linux/UNIX shell scripts via Cygwin/FreeBSD/Linux to do the same job)
- Added checksum validation (JSON manifest vs. downloaded .zip file) to updater script, to detect bad situations (e.g. network error, software bug, MITM, auto-JSON-updater on Mael's side somehow having a bug, etc.)

You can see the repository here: https://github.com/koitsu/chocolatey-packages/tree/master/hxd

If the Chocolatey Community Admins approve the ownership change, then the rest should act as normal.  (And we can consider adding language support to the PowerShell script bits after that.)

**Comment by TheCakeIsNaOH** [comment] 2022-12-14 16:59
> Chocolatey tends to prefer things be done this way now

Where did you read/hear this? 

It is still preferred (but not required) that packages on the Chocolatey Community Repository have the required files embedded inside the package instead of being downloaded at runtime. Assuming the resulting package is under 200mb and the software license allows redistribution.

**Comment by koitsu** [comment] 2022-12-14 17:06
> > Chocolatey tends to prefer things be done this way now
> 
> Where did you read/hear this?

It's hinted at somewhere within the Chocolatey documentation.  I will find it when I have time.

**Comment by koitsu** [comment] 2022-12-14 17:21
OK, the Chocolatey Community Admins have added me as a package maintainer.  I have a couple minor things to work out, but so far things are good.

@maelh The bits I have in place (commented out) for 2.5.0.0 with the updated JSON manifest are working fine locally.  Are you able to push out this change?

**Comment by koitsu** [comment] 2022-12-15 09:19
@AJDurant I've submitted the new HxD 2.5.0.0 package to the Chocolatey Community Repository.  From here on out it's the normal process of package updating + moderation/review + etc..

As such, I think we can close this ticket here, and if you run into Chocolatey hxd package issues in the future, file one here instead: https://github.com/koitsu/chocolatey-packages/issues

**Comment by koitsu** [comment] 2022-12-15 10:22
@TheCakeIsNaOH Now that this ticket is over with -- and even though it's off-topic -- I took the time to dig through the docs. 
 If you want to take this up on Discord instead of a GitHub ticket, I'm fine with that (I'm in the Chocolatey Discord, use koitsu#1732).  But here's the short and long version:

Short version: my comment ("...tends to prefer things be done this way...") stems from **how** the Chocolatey documentation on this subject is written.  The bottom line is that I chose my words poorly, and that my words do not accurately reflect the full situation.  However, the detailed answer below should explain (I think) why most package creators would not bother with including binaries within their .nupkg and instead just go with the fetch-from-remote approach.

Detailed version: it all boils down to licenses and distribution rights, as you are well aware.  But let's refer to Chocolatey documentation references I'm familiar with.  All emphases mine:

https://docs.chocolatey.org/en-us/information/legal#distributions

> **Most Chocolatey packages on the community feed (https://community.chocolatey.org/packages aka dot org) do not contain actual software distributions, only instructions for getting distributions (in PowerShell).** In a nutshell, the instructions are:
> * Download a distribution from remote location, most likely the published download location
> * Run an installer (possibly in silent mode)
>
> **Because this is no different than what a human would do, and b/c a human kicks off this process, it's reasonable to determine that there is no violation of distribution rights.**
> **In the cases where you would package the actual software in the package, please ensure you have distribution rights. Any package that is found on the community feed not in compliance will be removed immediately.** If you requested special permission to embed the software, make sure a copy of that permission is also in the package. If you are a software vendor that needs to report a violation, please see [a package is violating distribution rights](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-package-is-violating-distribution-rights).

https://docs.chocolatey.org/en-us/create/create-packages#including-the-software-installer-in-the-package

> Sometimes called embedding the binaries, there are functions in the automation scripts you can call that will use the installers directly from the package instead of downloading first. This makes for the most reliable and deterministic packages, **but ensure you have the [legal right to distribute](https://docs.chocolatey.org/en-us/information/legal) the software first if publishing to a public location (like the community package repository).**

https://docs.chocolatey.org/en-us/create/create-packages#rules-to-be-observed-before-publishing-packages

> Do not include software in a package that you don't have the right to distribute. Please see [Distribution Rights](https://docs.chocolatey.org/en-us/information/legal#distributions) for more information. **Any package found not in compliance with this will be removed immediately. Instead you can download binaries from official distribution locations at runtime.**

https://docs.chocolatey.org/en-us/create/functions/get-chocolateywebfile#notes
https://docs.chocolatey.org/en-us/create/functions/get-webfilename#notes
https://docs.chocolatey.org/en-us/create/functions/install-chocolateypackage#notes
https://docs.chocolatey.org/en-us/create/functions/install-chocolateypowershellcommand#notes
https://docs.chocolatey.org/en-us/create/functions/install-chocolateyzippackage#notes

> Chocolatey works best when the packages contain the software it is managing and doesn't require downloads. **However most software in the Windows world requires redistribution rights and when sharing packages publicly (like on the [community feed](https://community.chocolatey.org/packages)), maintainers may not have those aforementioned rights.** Chocolatey understands how to work with that, hence this function. You are not subject to this limitation with internal packages.

Opinionated summation:

The Chocolately documentation in this respect seems unsure of itself.  For example, quote: "most Chocolatey packages on the community feed do not contain actual software distributions, only instructions for getting distributions" -- this sentence, if true, implies that the fetch-from-remote-site methodology is the de-facto norm.  I would believe that to be the case for one simple reason: the mindset of most package maintainers (many of whom ARE NOT the authors of the software they're making packages for) works like this:

"So I either have to understand all the implications an faux-legalise of the license of the software I want to make a package for, so I can include the binary in the .nupkg, and risk legal action or violations if the license changes or I don't understand the license phrasing?  Or...  I can make my PS scripts fetch the binary from the remote server and never have to think about any of that?  Hmm, gosh, which should I choose?"

Chanting mantras like "reliable and most deterministic", "Chocolatey works best", and your aforementioned "preferred way" sound like marketing-speak and thus highly subjective.  They're turn-offs.  Likewise, I'm not aware of there being any objective study that prove these statements to be unconditionally true; maybe there's a blog post on it?  I don't know.  But I can delve into that matter if asked (warning: I've been a UNIX sysadmin for over 30 years and work heavily in DevOps/infrastructure, both bare-metal and cloud, *and* in networking), but for brevity sake I won't go into it here.

I say all this knowing quite well that the pre-included binary method guarantees that someone typing `choco install thingus` is guaranteed to get the software installed (assuming Chocolatey Community servers are up/reachable/Internet isn't broke), but I've given plenty of evidence as to why package maintainers might not want that responsibility.

If you want people to start pre-including binaries in their .nupkg packs, then it would do Chocolatey well to write a separate document (and a blog post to go along with it) that outlines in detail *why* that approach is better -- licensing permitted, of course.  Talk about your infrastructure, all the way down to aspects of redundancy, CDNs, HA (high-availability) infra, and so on.  I would go as far as to even recommend giving a real-world use-case for it, including a later blog post demonstrating how to switch from the fetch-from-remote model to the pre-included-in-nupkg model.  Don't just say "it's better" -- prove it's better and go from there.

**Closed as completed** 2022-12-15 12:08 UTC

**Comment by maelh** [comment] 2022-12-15 18:13
Thanks for taking over the HxD chocolatey package. Given how detailed your last comments were it looks like it is in good hands.

**Comment by maelh** [comment] 2022-12-15 18:16
@koitsu  Thanks for taking over the HxD chocolatey package. Given how detailed your last comments were it looks like it is in good hands.
